### ISSUE TITLE
[Doc Bug] Cirno image not showing up in bot documentation

### ISSUE THREAD

**Issue by 1Tartine** [LucientZ/DiscordPyBot#35]
**Describe the bug**
its not showing images

**To Reproduce**
the funny image needs to be in a directory 

**Expected behavior**
it will work

**Screenshots**
im blind cant help

**Desktop (please complete the following information):**
Microsoft Edge

**Smartphone (please complete the following information):**
i use a blackberry flip phone from 2003

**Additional context**

**Comment by LucientZ** [comment]
You mean this?

https://lucientz.github.io/DiscordPyBot/#fumo

**Comment by LucientZ** [comment]
Fixed with commit 862ac7e83f2f4dc62cf97c0919577705b9b740ab
